import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class SharedService {
   // 定義一個 BehaviorSubject 來存儲當前活動頁籤的資料
   private activeTabSource = new BehaviorSubject<string>('');

   // Observable 資料流
   activeTab = this.activeTabSource.asObservable();

   constructor() {}

   // 改變活動頁籤
   changeActiveTab(tab: string) {
     this.activeTabSource.next(tab);
   }

   // 取得臺灣各縣市，下拉選單要使用，value 是縣市代碼，text 是縣市名稱
    getTaiwanCounty() {
      return this.getCity();
      }


    // 臺灣各縣市名稱和縣市代碼
    getCity() {
      return [
        { value: 'A', text: '臺北市' },
        { value: 'F', text: '新北市' },
        { value: 'H', text: '桃園市' },
        { value: 'B', text: '臺中市' },
        { value: 'D', text: '臺南市' },
        { value: 'E', text: '高雄市' },
        { value: 'G', text: '宜蘭縣' },
        { value: 'J', text: '新竹縣' },
        { value: 'K', text: '苗栗縣' },
        { value: 'N', text: '彰化縣' },
        { value: 'M', text: '南投縣' },
        { value: 'P', text: '雲林縣' },
        { value: 'Q', text: '嘉義縣' },
        { value: 'T', text: '屏東縣' },
        { value: 'V', text: '臺東縣' },
        { value: 'U', text: '花蓮縣' },
        { value: 'X', text: '澎湖縣' },
        { value: 'W', text: '金門縣' },
        { value: 'Z', text: '連江縣' }
      ];
    };


     // 取得臺灣各縣市的鄰里或村，依 getCountyByCityId 的 行政區名稱當參數，value 是鄰里或村代碼，text 是鄰里或村名稱
    getTownshipByCountyId(countyId: string) {
      return this.getTownship(countyId);
    }

    getTownship(countyId: string) {
      switch (countyId) {
        case 'A':
          return [
            { value: 'A', text: '中正里' },
            { value: 'B', text: '光復里' },
            { value: 'C', text: '文北里' },
            { value: 'D', text: '文南里' },
            { value: 'E', text: '仁愛里' },
            { value: 'F', text: '仁和里' },
            { value: 'G', text: '仁義里' },
            { value: 'H', text: '仁信里' },
            { value: 'I', text: '仁勇里' },
            { value: 'J', text: '仁福里' },
            { value: 'K', text: '仁愛一里' },
            { value: 'L', text: '仁愛二里' },
            { value: 'M', text: '仁愛三里' },
            { value: 'N', text: '仁愛四里' },
            { value: 'O', text: '仁愛五里' },
            { value: 'P', text: '仁愛六里' },
            { value: 'Q', text: '仁愛七里' },
            { value: 'R', text: '仁愛八里' },
            { value: 'S', text: '仁愛九里' },
            { value: 'T', text: '仁愛十里' },
            { value: 'U', text: '仁愛十一里' },
            { value: 'V', text: '仁愛十二里' },
            { value: 'W', text: '仁愛十三里' },
            { value: 'X', text: '仁愛十四里' },
            { value: 'Y', text: '仁愛十五里' },
            { value: 'Z', text: '仁愛十六里' },
            { value: '1', text: '仁愛十七里' },
            { value: '2', text: '仁愛十八里' },
            { value: '3', text: '仁愛十九里' },
            { value: '4', text: '仁愛二十里' },
            { value: '5', text: '仁愛二十一里' },
            { value: '6', text: '仁愛二十二里' },
            { value: '7', text: '仁愛二十三里' },
            { value: '8', text: '仁愛二十四里' },
            { value: '9', text: '仁愛二十五里' },
            { value: '10', text: '仁愛二十六里' },
            { value: '11', text: '仁愛二十七里' },
            { value: '12', text: '仁愛二十八里' },
            { value: '13', text: '仁愛二十九里' },
            { value: '14', text: '仁愛三十里' },
            { value: '15', text: '仁愛三十一里' },
            { value: '16', text: '仁愛三十二里' },
            { value: '17', text: '仁愛三十三里' },
            { value: '18', text: '仁愛三十四里' },
            { value: '19', text: '仁愛三十五里' },
            { value: '20', text: '仁愛三十六里' },
            { value: '21', text: '仁愛三十七里' },
            { value: '22', text: '仁愛三十八里' },
            { value: '23', text: '仁愛三十九里' },
            { value: '24', text: '仁愛四十里' },
            { value: '25', text: '仁愛四十一里' },
            { value: '26', text: '仁愛四十二里' },
            { value: '27', text: '仁愛四十三里' },
            { value: '28', text: '仁愛四十四里' },
            { value: '29', text: '仁愛四十五里' },
            { value: '30', text: '仁愛四十六里' },
            { value: '31', text: '仁愛四十七里' },
            { value: '32', text: '仁愛四十八里' },
            { value: '33', text: '仁愛四十九里' },
            { value: '34', text: '仁愛五十里' },
            { value: '35', text: '仁愛五十一里' },
            { value: '36', text: '仁愛五十二里' },
            { value: '37', text: '仁愛五十三里' },
            { value: '38', text: '仁愛五十四里' },
            { value: '39', text: '仁愛五十五里' },
            { value: '40', text: '仁愛五十六里' },
            { value: '41', text: '仁愛五十七里' },
            { value: '42', text: '仁愛五十八里' },
            { value: '43', text: '仁愛五十九里' },
            { value: '44', text: '仁愛六十里' },
            { value: '45', text: '仁愛六十一里' },
            { value: '46', text: '仁愛六十二里' },
            { value: '47', text: '仁愛六十三里' },
            { value: '48', text: '仁愛六十四里' },
            { value: '49', text: '仁愛六十五里' },
            { value: '50', text: '仁愛六十六里' },
            { value: '51', text: '仁愛六十七里' },
            { value: '52', text: '仁愛六十八里' },
            { value: '53', text: '仁愛六十九里' },
            { value: '54', text: '仁愛七十里' },
            { value: '55', text: '仁愛七十一里' },
            { value: '56', text: '仁愛七十二里' },
            { value: '57', text: '仁愛七十三里' },
            { value: '58', text: '仁愛七十四里' },
            { value: '59', text: '仁愛七十五里' },
            { value: '60', text: '仁愛七十六里' },
            { value: '61', text: '仁愛七十七里' },
            { value: '62', text: '仁愛七十八里' },
            { value: '63', text: '仁愛七十九里' },
            { value: '64', text: '仁愛八十里' },
            { value: '65', text: '仁愛八十一里' },
            { value: '66', text: '仁愛八十二里' },
            { value: '67', text: '仁愛八十三里' },
            { value: '68', text: '仁愛八十四里' },
            { value: '69', text: '仁愛八十五里' },
            { value: '70', text: '仁愛八十六里' },
            { value: '71', text: '仁愛八十七里' },
            { value: '72', text: '仁愛八十八里' },
            { value: '73', text: '仁愛八十九里' },
            { value: '74', text: '仁愛九十里' },
            { value: '75', text: '仁愛九十一里' },
            { value: '76', text: '仁愛九十二里' },
            { value: '77', text: '仁愛九十三里' },
            { value: '78', text: '仁愛九十四里' },
            { value: '79', text: '仁愛九十五里' },
            { value: '80', text: '仁愛九十六里' },
            { value: '81', text: '仁愛九十七里' },
            { value: '82', text: '仁愛九十八里' },
            { value: '83', text: '仁愛九十九里' },
            { value: '84', text: '仁愛一百里' },
            { value: '85', text: '仁愛一百零一里' },
            { value: '86', text: '仁愛一百零二里' },
            { value: '87', text: '仁愛一百零三里' },
            { value: '88', text: '仁愛一百零四里' },
            { value: '89', text: '仁愛一百零五里' },
            { value: '90', text: '仁愛一百零六里' },
            { value: '91', text: '仁愛一百零七里' },
            { value: '92', text: '仁愛一百零八里' },
            { value: '93', text: '仁愛一百零九里' },
            { value: '94', text: '仁愛一百一十里' },
            { value: '95', text: '仁愛一百一十一里' },
            { value: '96', text: '仁愛一百一十二里' },
            { value: '97', text: '仁愛一百一十三里' },
            { value: '98', text: '仁愛一百一十四里' },
            { value : '99', text: '仁愛一百一十五里' },
            { value: '100', text: '仁愛一百一十六里' },
            { value: '101', text: '仁愛一百一十七里' },
            { value: '102', text: '仁愛一百一十八里' },
            { value: '103', text: '仁愛一百一十九里' },
            { value: '104', text: '仁愛一百二十里' },
            { value: '105', text: '仁愛一百二十一里' },
            { value: '106', text: '仁愛一百二十二里' },
            { value: '107', text: '仁愛一百二十三里' },
            { value: '108', text: '仁愛一百二十四里' },
            { value: '109', text: '仁愛一百二十五里' },
            { value: '110', text: '仁愛一百二十六里' },
            { value: '111', text: '仁愛一百二十七里' },
            { value: '112', text: '仁愛一百二十八里' },
            { value: '113', text: '仁愛一百二十九里' },
            { value: '114', text: '仁愛一百三十里' },
            { value: '115', text: '仁愛一百三十一里' },
            { value: '116', text: '仁愛一百三十二里' },
            { value: '117', text: '仁愛一百三十三里' },
            { value: '118', text: '仁愛一百三十四里' },
            { value: '119', text: '仁愛一百三十五里' },
            { value: '120', text: '仁愛一百三十六里' },
            { value: '121', text: '仁愛一百三十七里' },
            { value: '122', text: '仁愛一百三十八里' },
            { value: '123', text: '仁愛一百三十九里' },
            { value: '124', text: '仁愛一百四十里' },
            { value: '125', text: '仁愛一百四十一里' },
            { value: '126', text: '仁愛一百四十二里' },
            { value: '127', text: '仁愛一百四十三里' },
            { value: '128', text: '仁愛一百四十四里' },
            { value: '129', text: '仁愛一百四十五里' },
            { value: '130', text: '仁愛一百四十六里' },
            { value: '131', text: '仁愛一百四十七里' },
            { value: '132', text: '仁愛一百四十八里' },
            { value: '133', text: '仁愛一百四十九里' },
            { value: '134', text: '仁愛一百五十里' },
            { value: '135', text: '仁愛一百五十一里' },
            { value: '136', text: '仁愛一百五十二里' },
            { value: '137', text: '仁愛一百五十三里' },
            { value: '138', text: '仁愛一百五十四里' },
            { value: '139', text: '仁愛一百五十五里' },
            { value: '140', text: '仁愛一百五十六里' },
            { value: '141', text: '仁愛一百五十七里' },
            { value: '142', text: '仁愛一百五十八里' },
            { value: '143', text: '仁愛一百五十九里' }];
        case 'F':
          return [
            { value: 'A', text: '中正里' },
            { value: 'B', text: '光復里' },
            { value: 'C', text: '文北里' },
            { value: 'D', text: '文南里' },
            { value: 'E', text: '仁愛里' },
            { value: 'F', text: '仁和里' },
            { value: 'G', text: '仁義里' },
            { value: 'H', text: '仁信里' },
            { value: 'I', text: '仁勇里' },
            { value: 'J', text: '仁福里' },
            { value: 'K', text: '仁愛一里' },
            { value: 'L', text: '仁愛二里' },
            { value: 'M', text: '仁愛三里' },
            { value: 'N', text: '仁愛四里' },
            { value: 'O', text: '仁愛五里' },
            { value: 'P', text: '仁愛六里' },
            { value: 'Q', text: '仁愛七里' },
            { value: 'R', text: '仁愛八里' },
            { value: 'S', text: '仁愛九里' },
            { value: 'T', text: '仁愛十里' },
            { value: 'U', text: '仁愛十一里' },
            { value: 'V', text: '仁愛十二里' },
            { value: 'W', text: '仁愛十三里' },
            { value: 'X', text: '仁愛十四里' },
            { value: 'Y', text: '仁愛十五里' },
            { value: 'Z', text: '仁愛十六里' },
            { value: '1', text: '仁愛十七里' },
            { value: '2', text: '仁愛十八里' },
            { value: '3', text: '仁愛十九里' },
            { value: '4', text: '仁愛二十里' },
            { value: '5', text: '仁愛二十一里' },
            { value: '6', text: '仁愛二十二里' },
            { value: '7', text: '仁愛二十三里' },
            { value: '8', text: '仁愛二十四里' },
            { value: '9', text: '仁愛二十五里' },
            { value: '10', text: '仁愛二十六里' },
            { value: '11', text: '仁愛二十七里' },
            { value: '12', text: '仁愛二十八里' },
            { value: '13', text: '仁愛二十九里' },
            { value: '14', text: '仁愛三十里' },
            { value: '15', text: '仁愛三十一里' },
            { value: '16', text: '仁愛三十二里' },
            { value: '17', text: '仁愛三十三里' },
            { value: '18', text: '仁愛三十四里' },
            { value: '19', text: '仁愛三十五里' },
            { value: '20', text: '仁愛三十六里' },
            { value: '21', text: '仁愛三十七里' },
            { value: '22', text: '仁愛三十八里' },
            { value: '23', text: '仁愛三十九里' },
            { value: '24', text: '仁愛四十里' },
            { value: '25', text: '仁愛四十一里' },
            { value: '26', text: '仁愛四十二里' },
            { value: '27', text: '仁愛四十三里' }];
        case 'H':
          return [
            { value: 'A', text: '中正里' },
            { value: 'B', text: '光復里' },
            { value: 'C', text: '文北里' },
            { value: 'D', text: '文南里' },
            { value: 'E', text: '仁愛里' },
            { value: 'F', text: '仁和里' },
            { value: 'G', text: '仁義里' },
            { value: 'H', text: '仁信里' },
            { value: 'I', text: '仁勇里' },
            { value: 'J', text: '仁福里' },
            { value: 'K', text: '仁愛一里' },
            { value: 'L', text: '仁愛二里' },
            { value: 'M', text: '仁愛三里' },
            { value: 'N', text: '仁愛四里' },
            { value: 'O', text: '仁愛五里' },
            { value: 'P', text: '仁愛六里' },
            { value: 'Q', text: '仁愛七里' },
            { value: 'R', text: '仁愛八里' },
            { value: 'S', text: '仁愛九里' },
            { value: 'T', text: '仁愛十里' },
            { value: 'U', text: '仁愛十一里' },
            { value: 'V', text: '仁愛十二里' },
            { value: 'W', text: '仁愛十三里' },
            { value: 'X', text: '仁愛十四里' },
            { value: 'Y', text: '仁愛十五里' },
            { value: 'Z', text: '仁愛十六里' },
            { value: '1', text: '仁愛十七里' },
            { value: '2', text: '仁愛十八里' }];
        case 'B':
          return [
            { value: 'A', text: '中正里' },
            { value: 'B', text: '光復里' },
            { value: 'C', text: '文北里' },
            { value: 'D', text: '文南里' },
            { value: 'E', text: '仁愛里' },
            { value: 'F', text: '仁和里' },
            { value: 'G', text: '仁義里' },
            { value: 'H', text: '仁信里' },
            { value: 'I', text: '仁勇里' },
            { value: 'J', text: '仁福里' },
            { value: 'K', text: '仁愛一里' },
            { value: 'L', text: '仁愛二里' },
            { value: 'M', text: '仁愛三里' },
            { value: 'N', text: '仁愛四里' },
            { value: 'O', text: '仁愛五里' },
            { value: 'P', text: '仁愛六里' },
            { value: 'Q', text: '仁愛七里' },
            { value: 'R', text: '仁愛八里' },
            { value: 'S', text: '仁愛九里' },
            { value: 'T', text: '仁愛十里' },
            { value: 'U', text: '仁愛十一里' },
            { value: 'V', text: '仁愛十二里' },
            { value: 'W', text: '仁愛十三里' },
            { value: 'X', text: '仁愛十四里' },
            { value: 'Y', text: '仁愛十五里' }];
        case 'D':
          return [
            { value: 'A', text: '中正里' },
            { value: 'B', text: '光復里' },
            { value: 'C', text: '文北里' },
            { value: 'D', text: '文南里' },
            { value: 'E', text: '仁愛里' },
            { value: 'F', text: '仁和里' },
            { value: 'G', text: '仁義里' },
            { value: 'H', text: '仁信里' },
            { value: 'I', text: '仁勇里' },
            { value: 'J', text: '仁福里' },
            { value: 'K', text: '仁愛一里' },
            { value: 'L', text: '仁愛二里' },
            { value: 'M', text: '仁愛三里' },
            { value: 'N', text: '仁愛四里' },
            { value: 'O', text: '仁愛五里' },
            { value: 'P', text: '仁愛六里' },
            { value: 'Q', text: '仁愛七里' },
            { value: 'R', text: '仁愛八里' },
            { value: 'S', text: '仁愛九里' },
            { value: 'T', text: '仁愛十里' },
            { value: 'U', text: '仁愛十一里' },
            { value: 'V', text: '仁愛十二里' },
            { value: 'W', text: '仁愛十三里' },
            { value: 'X', text: '仁愛十四里' },
            { value: 'Y', text: '仁愛十五里' }];
        case 'E':
          return [
            { value: 'A', text: '中正里' },
            { value: 'B', text: '光復里' },
            { value: 'C', text: '文北里' },
            { value: 'D', text: '文南里' },
            { value: 'E', text: '仁愛里' },
            { value: 'F', text: '仁和里' },
            { value: 'G', text: '仁義里' },
            { value: 'H', text: '仁信里' },
            { value: 'I', text: '仁勇里' },
            { value: 'J', text: '仁福里' },
            { value: 'K', text: '仁愛一里' },
            { value: 'L', text: '仁愛二里' },
            { value: 'M', text: '仁愛三里' },
            { value: 'N', text: '仁愛四里' },
            { value: 'O', text: '仁愛五里' },
            { value: 'P', text: '仁愛六里' },
            { value: 'Q', text: '仁愛七里' },
            { value: 'R', text: '仁愛八里' },
            { value: 'S', text: '仁愛九里' },
            { value: 'T', text: '仁愛十里' },
            { value: 'U', text: '仁愛十一里' },
            { value: 'V', text: '仁愛十二里' },
            { value: 'W', text: '仁愛十三里' },
            { value: 'X', text: '仁愛十四里' },
            { value: 'Y', text: '仁愛十五里' }];
        case 'C':
          return [
            { value: 'A', text: '中正里' },
            { value: 'B', text: '光復里' },
            { value: 'C', text: '文北里' },
            { value: 'D', text: '文南里' },
            { value: 'E', text: '仁愛里' },
            { value: 'F', text: '仁和里' },
            { value: 'G', text: '仁義里' },
            { value: 'H', text: '仁信里' },
            { value: 'I', text: '仁勇里' },
            { value: 'J', text: '仁福里' },
            { value: 'K', text: '仁愛一里' },
            { value: 'L', text: '仁愛二里' },
            { value: 'M', text: '仁愛三里' },
            { value: 'N', text: '仁愛四里' },
            { value: 'O', text: '仁愛五里' },
            { value: 'P', text: '仁愛六里' },
            { value: 'Q', text: '仁愛七里' },
            { value: 'R', text: '仁愛八里' },
            { value: 'S', text: '仁愛九里' },
            { value: 'T', text: '仁愛十里' },
            { value: 'U', text: '仁愛十一里' },
            { value: 'V', text: '仁愛十二里' },
            { value: 'W', text: '仁愛十三里' },
            { value: 'X', text: '仁愛十四里' },
            { value: 'Y', text: '仁愛十五里' }];
        case 'G':
          return [
            { value: 'A', text: '中正里' },
            { value: 'B', text: '光復里' },
            { value: 'C', text: '文北里' },
            { value: 'D', text: '文南里' },
            { value: 'E', text: '仁愛里' },
            { value: 'F', text: '仁和里' },
            { value: 'G', text: '仁義里' },
            { value: 'H', text: '仁信里' },
            { value: 'I', text: '仁勇里' },
            { value: 'J', text: '仁福里' },
            { value: 'K', text: '仁愛一里' },
            { value: 'L', text: '仁愛二里' },
            { value: 'M', text: '仁愛三里' },
            { value: 'N', text: '仁愛四里' },
            { value: 'O', text: '仁愛五里' },
            { value: 'P', text: '仁愛六里' },
            { value: 'Q', text: '仁愛七里' },
            { value: 'R', text: '仁愛八里' },
            { value: 'S', text: '仁愛九里' },
            { value: 'T', text: '仁愛十里' },
            { value: 'U', text: '仁愛十一里' },
            { value: 'V', text: '仁愛十二里' },
            { value: 'W', text: '仁愛十三里' },
            { value: 'X', text: '仁愛十四里' },
            { value: 'Y', text: '仁愛十五里' }];
        case 'I':
          return [
            { value: 'A', text: '中正里' },
            { value: 'B', text: '光復里' },
            { value: 'C', text: '文北里' },
            { value: 'D', text: '文南里' },
            { value: 'E', text: '仁愛里' },
            { value: 'F', text: '仁和里' },
            { value: 'G', text: '仁義里' },
            { value: 'H', text: '仁信里' },
            { value: 'I', text: '仁勇里' },
            { value: 'J', text: '仁福里' },
            { value: 'K', text: '仁愛一里' },
            { value: 'L', text: '仁愛二里' },
            { value: 'M', text: '仁愛三里' },
            { value: 'N', text: '仁愛四里' },
            { value: 'O', text: '仁愛五里' },
            { value: 'P', text: '仁愛六里' },
            { value: 'Q', text: '仁愛七里' },
            { value: 'R', text: '仁愛八里' },
            { value: 'S', text: '仁愛九里' },
            { value: 'T', text: '仁愛十里' },
            { value: 'U', text: '仁愛十一里' },
            { value: 'V', text: '仁愛十二里' },
            { value: 'W', text: '仁愛十三里' },
            { value: 'X', text: '仁愛十四里' },
            { value: 'Y', text: '仁愛十五里' }];
        case 'J':
          return [
            { value: 'A', text: '中正里' },
            { value: 'B', text: '光復里' },
            { value: 'C', text: '文北里' },
            { value: 'D', text: '文南里' },
            { value: 'E', text: '仁愛里' },
            { value: 'F', text: '仁和里' },
            { value: 'G', text: '仁義里' },
            { value: 'H', text: '仁信里' },
            { value: 'I', text: '仁勇里' },
            { value: 'J', text: '仁福里' },
            { value: 'K', text: '仁愛一里' },
            { value: 'L', text: '仁愛二里' },
            { value: 'M', text: '仁愛三里' },
            { value: 'N', text: '仁愛四里' },
            { value: 'O', text: '仁愛五里' },
            { value: 'P', text: '仁愛六里' },
            { value: 'Q', text: '仁愛七里' },
            { value: 'R', text: '仁愛八里' },
            { value: 'S', text: '仁愛九里' },
            { value: 'T', text: '仁愛十里' },
            { value: 'U', text: '仁愛十一里' },
            { value: 'V', text: '仁愛十二里' },
            { value: 'W', text: '仁愛十三里' },
            { value: 'X', text: '仁愛十四里' },
            { value: 'Y', text: '仁愛十五里' }];
        case 'K':
          return [
            { value: 'A', text: '中正里' },
            { value: 'B', text: '光復里' },
            { value: 'C', text: '文北里' },
            { value: 'D', text: '文南里' },
            { value: 'E', text: '仁愛里' },
            { value: 'F', text: '仁和里' },
            { value: 'G', text: '仁義里' },
            { value: 'H', text: '仁信里' },
            { value: 'I', text: '仁勇里' },
            { value: 'J', text: '仁福里' },
            { value: 'K', text: '仁愛一里' },
            { value: 'L', text: '仁愛二里' },
            { value: 'M', text: '仁愛三里' },
            { value: 'N', text: '仁愛四里' },
            { value: 'O', text: '仁愛五里' },
            { value: 'P', text: '仁愛六里' },
            { value: 'Q', text: '仁愛七里' },
            { value: 'R', text: '仁愛八里' },
            { value: 'S', text: '仁愛九里' },
            { value: 'T', text: '仁愛十里' },
            { value: 'U', text: '仁愛十一里' },
            { value: 'V', text: '仁愛十二里' },
            { value: 'W', text: '仁愛十三里' },
            { value: 'X', text: '仁愛十四里' },
            { value: 'Y', text: '仁愛十五里' }];
        case 'L':
          return [
            { value: 'A', text: '中正里' },
            { value: 'B', text: '光復里' },
            { value: 'C', text: '文北里' },
            { value: 'D', text: '文南里' },
            { value: 'E', text: '仁愛里' },
            { value: 'F', text: '仁和里' },
            { value: 'G', text: '仁義里' },
            { value: 'H', text: '仁信里' },
            { value: 'I', text: '仁勇里' },
            { value: 'J', text: '仁福里' },
            { value: 'K', text: '仁愛一里' },
            { value: 'L', text: '仁愛二里' },
            { value: 'M', text: '仁愛三里' },
            { value: 'N', text: '仁愛四里' },
            { value: 'O', text: '仁愛五里' },
            { value: 'P', text: '仁愛六里' },
            { value: 'Q', text: '仁愛七里' },
            { value: 'R', text: '仁愛八里' },
            { value: 'S', text: '仁愛九里' },
            { value: 'T', text: '仁愛十里' },
            { value: 'U', text: '仁愛十一里' },
            { value: 'V', text: '仁愛十二里' },
            { value: 'W', text: '仁愛十三里' },
            { value: 'X', text: '仁愛十四里' },
            { value: 'Y', text: '仁愛十五里' }];
        default:
          return [];
      }
    }


    // 取得臺灣各縣市行政區，依 getCity method 縣市代碼當參數，text 是臺灣各縣市行政區名稱
    getCounty(countyId: string) {
      return this.getCountyByCityId(countyId);
    }

    getCountyByCityId(countyId: string) {
      switch (countyId) {
        case 'A':
          return [
            { value: 'A', text: '中正區' },
            { value: 'B', text: '大同區' },
            { value: 'C', text: '中山區' },
            { value: 'D', text: '松山區' },
            { value: 'E', text: '大安區' },
            { value: 'F', text: '萬華區' },
            { value: 'G', text: '信義區' },
            { value: 'H', text: '士林區' },
            { value: 'I', text: '北投區' },
            { value: 'J', text: '內湖區' },
            { value: 'K', text: '南港區' },
            { value: 'L', text: '文山區' }
          ];
        case 'F':
          return [
            { value: 'A', text: '板橋區' },
            { value: 'B', text: '三重區' },
            { value: 'C', text: '中和區' },
            { value: 'D', text: '永和區' },
            { value: 'E', text: '新莊區' },
            { value: 'F', text: '新店區' },
            { value: 'G', text: '樹林區' },
            { value: 'H', text: '鶯歌區' },
            { value: 'I', text: '三峽區' },
            { value: 'J', text: '淡水區' },
            { value: 'K', text: '汐止區' },
            { value: 'L', text: '瑞芳區' },
            { value: 'M', text: '土城區' },
            { value: 'N', text: '蘆洲區' },
            { value: 'O', text: '五股區' },
            { value: 'P', text: '泰山區' },
            { value: 'Q', text: '林口區' },
            { value: 'R', text: '深坑區' },
            { value: 'S', text: '石碇區' },
            { value: 'T', text: '坪林區' },
            { value: 'U', text: '三芝區' },
            { value: 'V', text: '石門區' },
            { value: 'W', text: '八里區' },
            { value: 'X', text: '平溪區' },
            { value: 'Y', text: '雙溪區' },
            { value: 'Z', text: '貢寮區' },
            { value: '1', text: '金山區' },
            { value: '2', text: '萬里區' },
            { value: '3', text: '烏來區' },
          ];
        case 'H':
          return [
            { value: 'A', text: '桃園區' },
            { value: 'B', text: '中壢區' },
            { value: 'C', text: '大溪區' },
            { value: 'D', text: '楊梅區' },
            { value: 'E', text: '蘆竹區' },
            { value: 'F', text: '大園區' },
            { value: 'G', text: '龜山區' },
            { value: 'H', text: '八德區' },
            { value: 'I', text: '龍潭區' },
            { value: 'J', text: '平鎮區' },
            { value: 'K', text: '新屋區' },
            { value: 'L', text: '觀音區' },
            { value: 'M', text: '復興區' },
          ];
        case 'B':
          return [
            { value: 'A', text: '中區' },
            { value: 'B', text: '東區' },
            { value: 'C', text: '南區' },
            { value: 'D', text: '西區' },
            { value: 'E', text: '北區' },
            { value: 'F', text: '北屯區' },
            { value: 'G', text: '西屯區' },
            { value: 'H', text: '南屯區' },
            { value: 'I', text: '太平區' },
            { value: 'J', text: '大里區' },
            { value: 'K', text: '霧峰區' },
            { value: 'L', text: '烏日區' },
            { value: 'M', text: '豐原區' },
            { value: 'N', text: '后里區' },
            { value: 'O', text: '石岡區' },
            { value: 'P', text: '東勢區' },
            { value: 'Q', text: '和平區' },
            { value: 'R', text: '新社區' },
            { value: 'S', text: '潭子區' },
            { value: 'T', text: '大雅區' },
            { value: 'U', text: '神岡區' },
            { value: 'V', text: '大肚區' },
            { value: 'W', text: '沙鹿區' },
            { value: 'X', text: '龍井區' },
            { value: 'Y', text: '梧棲區' },
            { value: 'Z', text: '清水區' },
            { value: '1', text: '大甲區' },
            { value: '2', text: '外埔區' },
            { value: '3', text: '大安區' },
          ];
        case 'D':
          return [
            { value: 'A', text: '中西區' },
            { value: 'B', text: '東區' },
            { value: 'C', text: '南區' },
            { value: 'D', text: '北區' },
            { value: 'E', text: '安平區' },
            { value: 'F', text: '安南區' },
            { value: 'G', text: '永康區' },
            { value: 'H', text: '歸仁區' },
            { value: 'I', text: '新化區' },
            { value: 'J', text: '左鎮區' },
            { value: 'K', text: '玉井區' },
            { value: 'L', text: '楠西區' },
            { value: 'M', text: '南化區' },
            { value: 'N', text: '仁德區' },
            { value: 'O', text: '關廟區' },
            { value: 'P', text: '龍崎區' },
            { value: 'Q', text: '官田區' },
            { value: 'R', text: '麻豆區' },
            { value: 'S', text: '佳里區' },
            { value: 'T', text: '西港區' },
            { value: 'U', text: '七股區' },
            { value: 'V', text: '將軍區' },
            { value: 'W', text: '學甲區' },
            { value: 'X', text: '北門區' },
            { value: 'Y', text: '新營區' },
            { value: 'Z', text: '後壁區' },
            { value: '1', text: '白河區' },
            { value: '2', text: '東山區' },
            { value: '3', text: '六 甲區' },
            { value: '4', text: '下營區' },
            { value: '5', text: '柳營區' },
            { value: '6', text: '鹽水區' },
            { value: '7', text: '善化區' },
            { value: '8', text: '大內區' },
            { value: '9', text: '山上區' },
            { value: '10', text: '新市區' },
            { value: '11', text: '安定區' },
          ];
        case 'E':
          return [
            { value: 'A', text: '新興區' },
            { value: 'B', text: '前金區' },
            { value: 'C', text: '苓雅區' },
            { value: 'D', text: '鹽埕區' },
            { value: 'E', text: '鼓山區' },
            { value: 'F', text: '旗津區' },
            { value: 'G', text: '前鎮區' },
            { value: 'H', text: '三民區' },
            { value: 'I', text: '楠梓區' },
            { value: 'J', text: '小港區' },
            { value: 'K', text: '左營區' },
            { value: 'L', text: '仁武區' },
            { value: 'M', text: '大社區' },
            { value: 'N', text: '岡山區' },
            { value: 'O', text: '路竹區' },
            { value: 'P', text: '阿蓮區' },
            { value: 'Q', text: '田寮區' },
            { value: 'R', text: '燕巢區' },
            { value: 'S', text: '橋頭區' },
            { value: 'T', text: '梓官區' },
            { value: 'U', text: '彌陀區' },
            { value: 'V', text: '永安區' },
            { value: 'W', text: '湖內區' },
            { value: 'X', text: '鳳山區' },
            { value: 'Y', text: '大寮區' },
            { value: 'Z', text: '林園區' },
            { value: '1', text: '鳥松區' },
            { value: '2', text: '大樹區 ' },
            { value: '3', text: '旗山區' },
            { value: '4', text: '美濃區' },
            { value: '5', text: '六龜區' },
            { value: '6', text: '內門區' },
            { value: '7', text: '杉林區' },
            { value: '8', text: '甲仙區' },
            { value: '9', text: '桃源區' },
            { value: '10', text: '那瑪夏區' },
            { value: '11', text: '茂林區' },
            { value: '12', text: '茄萣區' },
          ];
        case 'G':
          return [
            { value: 'A', text: '宜蘭市' },
            { value: 'B', text: '羅東鎮' },
            { value: 'C', text: '蘇澳鎮' },
            { value: 'D', text: '頭城鎮' },
            { value: 'E', text: '礁溪鄉' },
            { value: 'F', text: '壯圍鄉' },
            { value: 'G', text: '員山鄉' },
            { value: 'H', text: '冬山鄉' },
            { value: 'I', text: '五結鄉' },
            { value: 'J', text: '三星鄉' },
            { value: 'K', text: '大同鄉' },
            { value: 'L', text: '南澳鄉' },
          ];
        case 'J':
          return [
            { value: 'A', text: '竹北市' },
            { value: 'B', text: '竹東鎮' },
            { value: 'C', text: '新埔鎮' },
            { value: 'D', text: '關西鎮' },
            { value: 'E', text: '湖口鄉' },
            { value: 'F', text: '新豐鄉' },
            { value: 'G', text: '芎林鄉' },
            { value: 'H', text: '橫山鄉' },
            { value: 'I', text: '北埔鄉' },
            { value: 'J', text: '寶山鄉' },
            { value: 'K', text: '峨眉鄉' },
            { value: 'L', text: '尖石鄉' },
            { value: 'M', text: '五峰鄉' },
          ];
        case 'K':
          return [
            { value: 'A', text: '苗栗市' },
            { value: 'B', text: '頭份市' },
            { value: 'C', text: '竹南鎮' },
            { value: 'D', text: '後龍鎮' },
            { value: 'E', text: '通霄鎮' },
            { value: 'F', text: '苑裡鎮' },
            { value: 'G', text: '卓蘭鎮' },
            { value: 'H', text: '造橋鄉' },
            { value: 'I', text: '西湖鄉' },
            { value: 'J', text: '頭屋鄉' },
            { value: 'K', text: '公館鄉' },
            { value: 'L', text: '銅鑼鄉' },
            { value: 'M', text: '三義鄉' },
            { value: 'N', text: '大湖鄉' },
            { value: 'O', text: '獅潭鄉' },
            { value: 'P', text: '三灣鄉' },
            { value: 'Q', text: '南庄鄉' },
            { value: 'R', text: '泰安鄉' },
          ];
        case 'N':
          return [
            { value: 'A', text: '彰化市' },
            { value: 'B', text: '員林市' },
            { value: 'C', text: '和美鎮' },
            { value: 'D', text: '鹿港鎮' },
            { value: 'E', text: '溪湖鎮' },
            { value: 'F', text: '二林鎮' },
            { value: 'G', text: '田中鎮' },
            { value: 'H', text: '北斗鎮' },
            { value: 'I', text: '花壇鄉' },
            { value: 'J', text: '芬園鄉' },
            { value: 'K', text: '大村鄉' },
            { value: 'L', text: '永靖鄉' },
            { value: 'M', text: '伸港鄉' },
            { value: 'N', text: '線西鄉' },
            { value: 'O', text: '福興鄉' },
            { value: 'P', text: '秀水鄉' },
            { value: 'Q', text: '埔心鄉' },
            { value: 'R', text: '埔鹽鄉' },
            { value: 'S', text: '大城鄉' },
            { value: 'T', text: '芳苑鄉' },
            { value: 'U', text: '竹塘鄉' },
            { value: 'V', text: '社頭鄉' },
            { value: 'W', text: '二水鄉' },
            { value: 'X', text: '田尾鄉' },
            { value: 'Y', text: '埤頭鄉' },
            { value: 'Z', text: '溪州鄉' },
          ];
        case 'M':
          return [
            { value: 'A', text: '南投市' },
            { value: 'B', text: '埔里鎮' },
            { value: 'C', text: '草屯鎮' },
            { value: 'D', text: '竹山鎮' },
            { value: 'E', text: '集集鎮' },
            { value: 'F', text: '名間鄉' },
            { value: 'G', text: '鹿谷鄉' },
            { value: 'H', text: '中寮鄉' },
            { value: 'I', text: '魚池鄉' },
            { value: 'J', text: '國姓鄉' },
            { value: 'K', text: '水里鄉' },
            { value: 'L', text: '信義鄉' },
            { value: 'M', text: '仁愛鄉' },
          ];
        case 'P':
          return [
            { value: 'A', text: '斗六市' },
            { value: 'B', text: '斗南鎮' },
            { value: 'C', text: '虎尾鎮' },
            { value: 'D', text: '西螺鎮' },
            { value: 'E', text: '土庫鎮' },
            { value: 'F', text: '北港鎮' },
            { value: 'G', text: '古坑鄉' },
            { value: 'H', text: '大埤鄉' },
            { value: 'I', text: '莿桐鄉' },
            { value: 'J', text: '林內鄉' },
            { value: 'K', text: '二崙鄉' },
            { value: 'L', text: '崙背鄉' },
            { value: 'M', text: '麥寮鄉' },
            { value: 'N', text: '東勢鄉' },
            { value: 'O', text: '褒忠鄉' },
            { value: 'P', text: '臺西鄉' },
            { value: 'Q', text: '元長鄉' },
            { value: 'R', text: '四湖鄉' },
            { value: 'S', text: '口湖鄉' },
            { value: 'T', text: '水林鄉' },
          ];
        case 'Q':
          return [
            { value: 'A', text: '太保市' },
            { value: 'B', text: '朴子市' },
            { value: 'C', text: '布袋鎮' },
            { value: 'D', text: '大林鎮' },
            { value: 'E', text: '民雄鄉' },
            { value: 'F', text: '溪口鄉' },
            { value: 'G', text: '新港鄉' },
            { value: 'H', text: '六腳鄉' },
            { value: 'I', text: '東石鄉' },
            { value: 'J', text: '義竹鄉' },
            { value: 'K', text: '鹿草鄉' },
            { value: 'L', text: '水上鄉' },
            { value: 'M', text: '中埔鄉' },
            { value: 'N', text: '竹崎鄉' },
            { value: 'O', text: '梅山鄉' },
            { value: 'P', text: '番路鄉' },
            { value: 'Q', text: '大埔鄉' },
            { value: 'R', text: '阿里山鄉' },
          ];
        case 'T':
          return [
            { value: 'A', text: '屏東市' },
            { value: 'B', text: '潮州鎮' },
            { value: 'C', text: '東港鎮' },
            { value: 'D', text: '恆春鎮' },
            { value: 'E', text: '萬丹鄉' },
            { value: 'F', text: '長治鄉' },
            { value: 'G', text: '麟洛鄉' },
            { value: 'H', text: '九如鄉' },
            { value: 'I', text: '里港鄉' },
            { value: 'J', text: '鹽埔鄉' },
            { value: 'K', text: '高樹鄉' },
            { value: 'L', text: '萬巒鄉' },
            { value: 'M', text: '內埔鄉' },
            { value: 'N', text: '竹田鄉' },
            { value: 'O', text: '新埤鄉' },
            { value: 'P', text: '枋寮鄉' },
            { value: 'Q', text: '新園鄉' },
            { value: 'R', text: '崁頂鄉' },
            { value: 'S', text: '林邊鄉' },
            { value: 'T', text: '南州鄉' },
            { value: 'U', text: '佳冬鄉' },
            { value: 'V', text: '琉球鄉' },
            { value: 'W', text: '車城鄉' },
            { value: 'X', text: '滿州鄉' },
            { value: 'Y', text: '枋山鄉' },
            { value: 'Z', text: '三地門鄉' },
            { value: '1', text: ' 霧臺鄉' },
            { value: '2', text: ' 瑪家鄉' },
            { value: '3', text: ' 泰武鄉' },
            { value: '4', text: ' 來義鄉' },
            { value: '5', text: ' 春日鄉' },
            { value: '6', text: ' 獅子鄉' },
            { value: '7', text: ' 牡丹鄉' },
            { value: '8', text: ' 禮北鄉' },
            { value: '9', text: ' 巨里鄉' },
            { value: '10', text: ' 大武鄉' },
            { value: '11', text: ' 太麻里鄉' },
          ];
        case 'V':
          return [
            { value: 'A', text: '臺東市' },
            { value: 'B', text: '成功鎮' },
            { value: 'C', text: '關山鎮' },
            { value: 'D', text: '卑南鄉' },
            { value: 'E', text: '大武鄉' },
            { value: 'F', text: '太麻里鄉' },
            { value: 'G', text: '東河鄉' },
            { value: 'H', text: '長濱鄉' },
            { value: 'I', text: '鹿野鄉' },
            { value: 'J', text: '池上鄉' },
            { value: 'K', text: '綠島鄉' },
            { value: 'L', text: '延平鄉' },
            { value: 'M', text: '海端鄉' },
            { value: 'N', text: '達仁鄉' },
            { value: 'O', text: '金峰鄉' },
            { value: 'P', text: '蘭嶼鄉' },
          ];
        case 'U':
          return [
            { value: 'A', text: '花蓮市' },
            { value: 'B', text: '鳳林鎮' },
            { value: 'C', text: '玉里鎮' },
            { value: 'D', text: '新城鄉' },
            { value: 'E', text: '吉安鄉' },
            { value: 'F', text: '壽豐鄉' },
            { value: 'G', text: '光復鄉' },
            { value: 'H', text: '豐濱鄉' },
            { value: 'I', text: '瑞穗鄉' },
            { value: 'J', text: '富里鄉' },
            { value: 'K', text: '秀林鄉' },
            { value: 'L', text: '萬榮鄉' },
            { value: 'M', text: '卓溪鄉' },
          ];
        case 'Z':
          return [
            { value: 'A', text: '南竿鄉' },
            { value: 'B', text: '北竿鄉' },
            { value: 'C', text: '莒光鄉' },
            { value: 'D', text: '東引鄉' },
          ];
        case 'W':
          return [
            { value: 'A', text: '金城鎮' },
            { value: 'B', text: '金沙鎮' },
            { value: 'C', text: '金湖鎮' },
            { value: 'D', text: '金寧鄉' },
            { value: 'E', text: '烈嶼鄉' },
            { value: 'F', text: '烏坵鄉' },
          ];
        case 'X':
          return [
            { value: 'A', text: '馬公市' },
            { value: 'B', text: '西嶼鄉' },
            { value: 'C', text: '望安鄉' },
            { value: 'D', text: '七美鄉' },
            { value: 'E', text: '白沙鄉' },
            { value: 'F', text: '湖西鄉' },
          ];
        default:
          return [];
        }
    }
}
